Enhance CI workflow with DLL checks and artifact uploads

diff --git a/.github/workflows/qemu-woa64-msys-clangarm64.yml b/.github/workflows/qemu-woa64-msys-clangarm64.yml
--- a/.github/workflows/qemu-woa64-msys-clangarm64.yml
+++ b/.github/workflows/qemu-woa64-msys-clangarm64.yml
@@ -85,11 +85,34 @@ jobs:
 
       - name: Where are my dependent dlls?
         continue-on-error: false
+        id: test_lib_dll
         run: |
           which -a  libpng16-16.dll
           which -a  libgnutls-30.dll
           which -a  libcapstone.dll
           which -a  libpixman-1-0.dll
+
+
+      - name: Check if command exists
+        id: test_objdump
+        run: |
+          if command -v x86_64-w64-mingw32-objdump &> /dev/null; then
+            which -a x86_64-w64-mingw32-objdump
+          else
+            echo "x86_64-w64-mingw32-objdump does not exist!"
+            exit 1
+          fi
+
+      - name: Upload Build Artifacts to debug runtime
+        uses: actions/upload-artifact@v7
+        if: steps.test_objdump.outcome != 'success' || steps.test_lib_dll.outcome != 'success'
+        with:
+          name: clangarm64-bin-debug-pack-${{ github.run_number }}       # The name of your downloadable zip file
+          path: /clangarm64/bin           # The directory or file path to upload
+          retention-days: 1            # Optional: How long to keep the files (Default: 90)
+          if-no-files-found: error     # Optional: Fails the build if 'dist' is missing
+
+      
           
       - name: Verify Compiler
         run: |
@@ -101,6 +124,8 @@ jobs:
           echo "docs build is still disabled"
 
       - name: Build Project
+        id: main_build
+        if: steps.test_objdump.outcome == 'success' && steps.test_lib_dll.outcome == 'success'
         run: |
           export CC=clang
           export CXX=clang++
@@ -108,6 +133,7 @@ jobs:
           make
           
       - name: try build installer
+        if: steps.main_build.outcome == 'success' 
         run: |
           date=$(date +%Y%m%d)
           mkdir dist
@@ -121,7 +147,7 @@ jobs:
       #debugging ci workflow
       - name: Upload Build Artifacts
         uses: actions/upload-artifact@v7
-        if: always()
+        if: steps.main_build.outcome == 'success' 
         with:
           name: buildonly-clangarm64-msys2-${{ github.run_number }}       # The name of your downloadable zip file
           path: ./build/           # The directory or file path to upload
